# -*- coding: utf-8 -*-
"""urdu sentmentINDDL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JsJHNpiNltCiEmNXBgbSs5Kv5vYSB-tt
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/urdu sentiments

import pandas as pd
import numpy as np



train=pd.read_csv('trainHYBRID.csv')

test=pd.read_csv('testHYBRID.csv')

y_train=train['class']
X_train=train.drop(['Unnamed: 0','class'],axis=1)

y_test=test['class']
X_test=test.drop(['Unnamed: 0','class'],axis=1)

df=pd.concat([train,test],axis=0)
df=df.reset_index(drop=True)

y=df['class']
X=df.drop(['Unnamed: 0','class'],axis=1)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, make_scorer
from sklearn.model_selection import cross_val_score, StratifiedKFold, KFold, LeaveOneOut, train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import RidgeClassifier, Perceptron
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
# from catboost import CatBoostClassifier
import numpy as np
import tensorflow as tf
from keras.models import Sequential
import urllib.request

from keras.layers import Dense, Dropout, Embedding, Conv1D, MaxPooling1D, GlobalMaxPooling1D, Flatten, LSTM, GRU, SimpleRNN
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from tensorflow.keras.models import Model
import keras

# from tensorflow.keras.models import load_model

# modelcnn = load_model('best_modelfcnurdu.h5')

y_pred = modelcnn.predict(X_test)
from sklearn.metrics import f1_score, recall_score
# Convert predictions to class labels
y_pred_labels = np.argmax(y_pred, axis=1)
# y_true_labels = np.argmax(y_test, axis=1)
# predicted_labels = [1 if pred > 0.5 else 0 for pred in y_pred]

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_labels)
print(accuracy)
# Calculate F1 score
f1 = f1_score(y_test, y_pred_labels)
print(f1)
# Calculate recall
recall = recall_score(y_test, y_pred_labels)
recall



import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten

# Define the FCNN model
model = tf.keras.Sequential([
    Flatten(input_shape=(1324,)),  # Flatten the input sequence
    Dense(64, activation='sigmoid'),  # First fully-connected layer with 64 units and ReLU activation
    Dense(32, activation='sigmoid'),  # Second fully-connected layer with 32 units and ReLU activation
    Dense(2, activation='softmax')  # Output layer with 'num_classes' units and softmax activation
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
# model.fit(X_train, y_train, batch_size=32, epochs=20, validation_data=(X_test, y_test))

# # Evaluate the model
# loss, accuracy = model.evaluate(X_test, y_test)

# # Make predictions
# predictions = model.predict(X_test)

from keras.callbacks import ModelCheckpoint

fcncheckpoint = ModelCheckpoint('best_modelfcnurdu.h5', monitor='val_accuracy', save_best_only=True, mode='max', verbose=1)

model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test),callbacks=[fcncheckpoint])

from sklearn.metrics import accuracy_score, f1_score, recall_score
y_pred = modelcnn.predict(X_test)

# Convert predictions to class labels
# predicted_labels = [1 if pred > 0.5 else 0 for pred in y_pred]

predicted_labels = np.argmax(y_pred, axis=1)

# y_pred = modelcnn.predict(X_test)
from sklearn.metrics import f1_score, recall_score
# Convert predictions to class labels
# y_pred_labels = np.argmax(y_pred, axis=1)
# y_true_labels = np.argmax(y_test, axis=1)
# predicted_labels = [1 if pred > 0.5 else 0 for pred in y_pred]

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_labels)
print(accuracy)
# Calculate F1 score
f1 = f1_score(y_test, y_pred_labels)
print(f1)
# Calculate recall
recall = recall_score(y_test, y_pred_labels)
recall

# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)
print(accuracy)

# Calculate F1 score
f1 = f1_score(y_test, predicted_labels)
print(f1)

# Calculate recall
recall = recall_score(y_test, predicted_labels)
print(recall)



from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Assuming you have trained and obtained the predicted probabilities from your FCN model
y_pred_prob = modelcnn.predict(X_test)

# Compute the false positive rate (FPR), true positive rate (TPR), and threshold values
fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)

# Compute the Area Under the ROC Curve (AUC)
auc = roc_auc_score(y_test, y_pred_prob)

# Plot the ROC curve
plt.plot(fpr, tpr, label=f'ROC Curve (AUC = {auc:.4f})')
plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line representing random classifier
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend()
plt.show()

y_test

# n_timesteps, n_features, n_outputs = X_train.shape[1], X_train.shape[2], trainy.shape[1]

pip install keras-tuner

# import tensorflow as tf
# from tensorflow import keras
# from tensorflow.keras import layers
# from kerastuner.tuners import RandomSearch

# # Define the number of classes and input shape
# num_classes = 2
# input_shape = (1324, 1)

# # Define the CNN model
# def build_model(hp):
#     model = keras.Sequential()

#     # Define the model architecture
#     model.add(layers.Conv1D(filters=hp.Int('filters', min_value=32, max_value=512, step= 16),
#                             kernel_size=hp.Choice('kernel_size', values=[1,3, 5, 7,9]),
#                             activation='relu',
#                             input_shape=input_shape))
#     model.add(layers.MaxPooling1D(pool_size=2))

#     model.add(layers.Conv1D(filters=hp.Int('filters', min_value=16, max_value=256, step= 8),
#                             kernel_size=hp.Choice('kernel_size', values=[1,3, 5, 7,9]),
#                             activation='relu',
#                             input_shape=input_shape))

#     model.add(layers.MaxPooling1D(pool_size=2))

#     model.add(layers.Flatten())
#     model.add(layers.Dense(units=hp.Int('dense_units', min_value=64, max_value=256, step=32), activation='relu'))
#     model.add(layers.Dense(num_classes, activation='softmax'))

#     # Define the optimizer and learning rate
#     optimizer = keras.optimizers.Adam(learning_rate=hp.Float('learning_rate', min_value=1e-4, max_value=1e-2, sampling='LOG'))

#     # Compile the model
#     model.compile(optimizer=optimizer,
#                   loss='categorical_crossentropy',
#                   metrics=['accuracy'])

#     return model

# # Create the tuner
# tuner = RandomSearch(
#     build_model,
#     objective='val_accuracy',
#     max_trials=10,
#     directory='1dcnn_tuner',
#     project_name='cnnurdu'
# )

# # Start the tuner search
# tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

# # Get the best model
# best_modelcnn = tuner.get_best_models(1)[0]
# best_hyperparameterscnn = tuner.get_best_hyperparameters(1)[0]





modelcnn = Sequential()
modelcnn.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(1324,1)))
modelcnn.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
modelcnn.add(Dropout(0.5))
modelcnn.add(MaxPooling1D(pool_size=2))
modelcnn.add(Flatten())
modelcnn.add(Dense(100, activation='relu'))
modelcnn.add(Dropout(0.5))
modelcnn.add(Dense(50, activation='relu'))
modelcnn.add(Dense(1, activation='sigmoid'))
modelcnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

from keras.callbacks import ModelCheckpoint

# Define the ModelCheckpoint callback
checkpoint = ModelCheckpoint('best_modelcnnurdu.h5', monitor='val_accuracy', save_best_only=True, mode='max', verbose=1)

# Train the model and save the best model based on validation loss
modelcnn.fit(X_train, y_train, epochs=20, batch_size=64, verbose=1,validation_data=(X_test,y_test), callbacks=[checkpoint])

loss, accuracy = modelcnn.evaluate(X_test, y_test)
accuracy

from keras.models import load_model

# Load the best model
best_model = load_model('best_modelcnnurdu.h5')

# Predict test data
predictionscnn = best_model.predict(X_test)

# Convert predictions to class labels
predicted_labels = [1 if pred > 0.5 else 0 for pred in predictionscnn]

# Print the predicted labels
# print(predicted_labels)
accuracy_score(y_test,predicted_labels)

y_pred = best_model.predict(X_test)
from sklearn.metrics import f1_score,recall_score
# Convert predictions to class labels
# y_pred_labels = tf.argmax(y_pred, axis=1)
# y_true_labels = tf.argmax(y_test, axis=1)

# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)
print(accuracy)
# Calculate F1 score
f1 = f1_score(y_test, predicted_labels)
print(f1)
# Calculate recall
recall = recall_score(y_test, predicted_labels)
recall

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Assuming you have trained and obtained the predicted probabilities from your FCN model
y_pred_prob = model.predict(X_test)

# Compute the false positive rate (FPR), true positive rate (TPR), and threshold values
fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)

# Compute the Area Under the ROC Curve (AUC)
auc = roc_auc_score(y_test, y_pred_prob)

# Plot the ROC curve
plt.plot(fpr, tpr, label=f'ROC Curve (AUC = {auc:.4f})')
plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line representing random classifier
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend()
plt.show()

predicted_labelscnn = [1 if pred > 0.5 else 0 for pred in predictionscnn]
predicted_labels = [1 if pred > 0.5 else 0 for pred in predictions]

trainx=np.array(X_train)
testx=np.array(X_test)
trainx = np.reshape(trainx, (trainx.shape[0], 1, trainx.shape[1]))
testx = np.reshape(testx, (testx.shape[0], 1, testx.shape[1]))



# Reshape input data
input_dim=1324
from sklearn.metrics import confusion_matrix
import tensorflow as tf
# trainx = trainx.reshape(-1, input_dim)
# testx = testx.reshape(-1, input_dim)

# # Convert output data to one-hot encoding
y_train = tf.keras.utils.to_categorical(y_train, 2)
y_test = tf.keras.utils.to_categorical(y_test, 2)

from keras.layers import LSTM, Dense, Dropout
num_timesteps,num_features=1,1324
lstm = Sequential()
lstm.add(LSTM(units=128, input_shape=(num_timesteps, num_features)))
lstm.add(Dropout(0.5))  # Add dropout layer for regularization
lstm.add(Dense(units=64, activation='relu'))  # Add additional dense layer
lstm.add(Dropout(0.5))  # Add dropout layer for regularization
lstm.add(Dense(units=32, activation='relu'))  # Add additional dense layer
lstm.add(Dropout(0.5))  # Add dropout layer for regularization
lstm.add(Dense(units=2, activation='softmax'))
lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

from keras.callbacks import ModelCheckpoint

lstmcheckpoint = ModelCheckpoint('best_modellstmurdu.h5', monitor='val_accuracy', save_best_only=True, mode='max', verbose=1)

lstm.fit(trainx, y_train, epochs=100, validation_data=(testx, y_test),callbacks=[lstmcheckpoint])

from tensorflow import keras
from sklearn.metrics import accuracy_score, matthews_corrcoef, precision_score, recall_score


best_modellstm = keras.models.load_model('best_modellstmurdu.h5')
predictions = best_modellstm.predict(testx)


# Get the predictions from the best model
y_test_pred = best_modellstm.predict(testx)

# Convert the predictions to binary labels
y_test_pred_labels = np.argmax(y_test_pred, axis=1)

# Convert the true labels to binary labels
y_test_true_labels = np.argmax(y_test, axis=1)

# Calculate accuracy
test_accuracy = accuracy_score(y_test_true_labels, y_test_pred_labels)

# Calculate MCC
test_mcc = matthews_corrcoef(y_test_true_labels, y_test_pred_labels)

# Calculate specificity
test_specificity = recall_score(y_test_true_labels, y_test_pred_labels, pos_label=0)

# Calculate sensitivity
test_sensitivity = recall_score(y_test_true_labels, y_test_pred_labels, pos_label=1)
print("LSTM")
print("Test Accuracy:", test_accuracy)
print("Test MCC:", test_mcc)
print("Test Specificity:", test_specificity)
print("Test Sensitivity:", test_sensitivity)

f1 = f1_score(y_test_true_labels, y_test_pred_labels)
f1



from keras.layers import LSTM, Dense, Dropout, GRU

gru = Sequential()
gru.add(GRU(units=256, input_shape=(1, 1324)))
gru.add(Dropout(0.5))  # Add dropout layer for regularization
gru.add(Dense(units=128, activation='relu'))  # Add additional dense layer
gru.add(Dropout(0.5))  # Add dropout layer for regularization
gru.add(Dense(units=2, activation='softmax'))
gru.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

from keras.callbacks import ModelCheckpoint

grucheckpoint = ModelCheckpoint('best_modelgruurdu.h5', monitor='val_accuracy', save_best_only=True, mode='max', verbose=1)

gru.fit(trainx, y_train, epochs=100, validation_data=(testx, y_test),callbacks=[grucheckpoint])

from tensorflow import keras
from sklearn.metrics import accuracy_score, matthews_corrcoef, precision_score, recall_score


best_modelgru = keras.models.load_model('best_modelgruurdu.h5')
predictions = best_modelgru.predict(testx)


# Get the predictions from the best model
y_test_pred = best_modelgru.predict(testx)

# Convert the predictions to binary labels
y_test_pred_labels = np.argmax(y_test_pred, axis=1)

# Convert the true labels to binary labels
y_test_true_labels = np.argmax(y_test, axis=1)

# Calculate accuracy
test_accuracy = accuracy_score(y_test_true_labels, y_test_pred_labels)

# Calculate MCC
test_mcc = matthews_corrcoef(y_test_true_labels, y_test_pred_labels)

# Calculate specificity
test_specificity = recall_score(y_test_true_labels, y_test_pred_labels, pos_label=0)

# Calculate sensitivity
test_sensitivity = recall_score(y_test_true_labels, y_test_pred_labels, pos_label=1)
print("GRU")
print("Test Accuracy:", test_accuracy)
print("Test MCC:", test_mcc)
print("Test Specificity:", test_specificity)
print("Test Sensitivity:", test_sensitivity)

from tensorflow import keras
from sklearn.metrics import accuracy_score, matthews_corrcoef, precision_score, recall_score


best_modelgru = keras.models.load_model('best_modellstmurdu.h5')
predictions = best_modelgru.predict(testx)


# Get the predictions from the best model
y_test_pred = best_modelgru.predict(testx)

# Convert the predictions to binary labels
y_test_pred_labels = np.argmax(y_test_pred, axis=1)

# Convert the true labels to binary labels
y_test_true_labels = np.argmax(y_test, axis=1)

# Calculate accuracy
test_accuracy = accuracy_score(y_test_true_labels, y_test_pred_labels)

# Calculate MCC
test_mcc = matthews_corrcoef(y_test_true_labels, y_test_pred_labels)

# Calculate specificity
test_specificity = recall_score(y_test_true_labels, y_test_pred_labels, pos_label=0)

# Calculate sensitivity
test_sensitivity = recall_score(y_test_true_labels, y_test_pred_labels, pos_label=1)
print("LSTM")
print("Test Accuracy:", test_accuracy)
print("Test MCC:", test_mcc)
print("Test Specificity:", test_specificity)
print("Test Sensitivity:", test_sensitivity)

from tensorflow import keras
from sklearn.metrics import accuracy_score, matthews_corrcoef, precision_score, recall_score


best_modelgru = keras.models.load_model('best_modelfcnurdu.h5')
predictions = best_modelgru.predict(X_test)


# Get the predictions from the best model
y_test_pred = best_modelgru.predict(X_test)

# Convert the predictions to binary labels
y_test_pred_labels = np.argmax(y_test_pred, axis=1)

# Convert the true labels to binary labels
# y_test_true_labels = np.argmax(y_test, axis=1)

# Calculate accuracy
test_accuracy = accuracy_score(y_test, y_test_pred_labels)

# Calculate MCC
test_mcc = matthews_corrcoef(y_test, y_test_pred_labels)

# Calculate specificity
test_specificity = recall_score(y_test, y_test_pred_labels, pos_label=0)

# Calculate sensitivity
test_sensitivity = recall_score(y_test, y_test_pred_labels, pos_label=1)
print("FCN")
print("Test Accuracy:", test_accuracy)
print("Test MCC:", test_mcc)
print("Test Specificity:", test_specificity)
print("Test Sensitivity:", test_sensitivity)

fcn_pred = fcn.predict(X_test)
cnn_pred = cnn.predict(X_test)
lstm_pred = lstm.predict(testx)
fru_pred = fru.predict(testx)

fru_pred

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Load the saved models (assuming they are stored as fcn_model.h5, cnn_model.h5, lstm_model.h5, and fru_model.h5)
# fcn = keras.models.load_model('fcn_model.h5')
# cnn = keras.models.load_model('cnn_model.h5')
# lstm = keras.models.load_model('lstm_model.h5')
# fru = keras.models.load_model('fru_model.h5')

# Assuming you have test data (X_test and y_test) for evaluation
# X_test = ...
# y_test = ...

# Make predictions using each model
fcn_pred = fcn.predict(X_test)
cnn_pred = cnn.predict(X_test)
lstm_pred = lstm.predict(testx)
fru_pred = fru.predict(testx)

# Convert predictions to binary class labels (assuming binary classification)
# fcn_pred_labels = np.round(fcn_pred).flatten()
# cnn_pred_labels = np.round(cnn_pred).flatten()
# lstm_pred_labels = np.round(lstm_pred).flatten()
# fru_pred_labels = np.round(fru_pred).flatten()

fcn_pred_labels = np.argmax(fcn_pred, axis=1)
cnn_pred_labels=np.round(cnn_pred).astype(int)
lstm_pred_labels = np.argmax(lstm_pred, axis=1)
fru_pred_labels = np.argmax(fru_pred, axis=1)


# Compute evaluation metrics for each model
fcn_accuracy = accuracy_score(y_test, fcn_pred_labels)
fcn_precision = precision_score(y_test, fcn_pred_labels)
fcn_recall = recall_score(y_test, fcn_pred_labels)
fcn_f1_score = f1_score(y_test, fcn_pred_labels)

cnn_accuracy = accuracy_score(y_test, cnn_pred_labels)
cnn_precision = precision_score(y_test, cnn_pred_labels)
cnn_recall = recall_score(y_test, cnn_pred_labels)
cnn_f1_score = f1_score(y_test, cnn_pred_labels)

lstm_accuracy = accuracy_score(y_test, lstm_pred_labels)
lstm_precision = precision_score(y_test, lstm_pred_labels)
lstm_recall = recall_score(y_test, lstm_pred_labels)
lstm_f1_score = f1_score(y_test, lstm_pred_labels)

fru_accuracy = accuracy_score(y_test, fru_pred_labels)
fru_precision = precision_score(y_test, fru_pred_labels)
fru_recall = recall_score(y_test, fru_pred_labels)
fru_f1_score = f1_score(y_test, fru_pred_labels)

# Print the evaluation metrics for each model
print("FCN - Accuracy:", fcn_accuracy)
print("FCN - Precision:", fcn_precision)
print("FCN - Recall:", fcn_recall)
print("FCN - F1 Score:", fcn_f1_score)
print()
print("CNN - Accuracy:", cnn_accuracy)
print("CNN - Precision:", cnn_precision)
print("CNN - Recall:", cnn_recall)
print("CNN - F1 Score:", cnn_f1_score)
print()
print("LSTM - Accuracy:", lstm_accuracy)
print("LSTM - Precision:", lstm_precision)
print("LSTM - Recall:", lstm_recall)
print("LSTM - F1 Score:", lstm_f1_score)
print()
print("FRU - Accuracy:", fru_accuracy)
print("FRU - Precision:", fru_precision)
print("FRU - Recall:", fru_recall)
print("FRU - F1 Score:", fru_f1_score)

from tabulate import tabulate

# Define the evaluation metrics for each model
models = ['FCN', 'CNN', 'LSTM', 'FRU']
accuracy = [0.8558917197452229, 0.857484076433121, 0.8598726114649682, 0.8598726114649682]
precision = [0.8627450980392157, 0.8738255033557047, 0.8825136612021858, 0.8655352480417755]
recall = [0.8967391304347826, 0.8845108695652174, 0.8777173913043478, 0.9008152173913043]
f1_score = [0.8794137241838774, 0.8791357191087105, 0.8801089918256131, 0.8828229027962717]

# Round the evaluation metrics to three decimal places
accuracy = [round(metric, 3) for metric in accuracy]
precision = [round(metric, 3) for metric in precision]
recall = [round(metric, 3) for metric in recall]
f1_score = [round(metric, 3) for metric in f1_score]

# Create a list of lists for the table data
table_data = list(zip(models, accuracy, precision, recall, f1_score))

# Generate the table
table = tabulate(table_data, headers=['Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score'], tablefmt='pipe')

# Print the table
print(table)

fcn.predict(X_test)[:, 1]

import numpy as np
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Load the saved models (assuming they are stored as fcn_model.h5, cnn_model.h5, lstm_model.h5, and fru_model.h5)
fcn = keras.models.load_model('best_modelfcnurdu.h5')
cnn = keras.models.load_model('best_modelcnnurdu.h5')
lstm = keras.models.load_model('best_modellstmurdu.h5')
fru = keras.models.load_model('best_modelgruurdu.h5')

# Assuming you have test data (X_test and y_test) for evaluation
# X_test = ...
# y_test = ...

# Get the predicted probabilities from each model
# fcn_pred_prob = fcn.predict(X_test)
# cnn_pred_prob = cnn.predict(X_test)
# lstm_pred_prob = lstm.predict(testx)
# fru_pred_prob = fru.predict(test)

fcn_pred_prob = fcn.predict(X_test)[:, 1]
cnn_pred_prob = cnn.predict(X_test)[:, 0]
lstm_pred_prob = lstm.predict(testx)[:, 1]
fru_pred_prob = fru.predict(testx)[:, 1]


# Compute the false positive rate (FPR), true positive rate (TPR), and threshold values for each model
fcn_fpr, fcn_tpr, fcn_thresholds = roc_curve(y_test, fcn_pred_prob)
cnn_fpr, cnn_tpr, cnn_thresholds = roc_curve(y_test, cnn_pred_prob)
lstm_fpr, lstm_tpr, lstm_thresholds = roc_curve(y_test, lstm_pred_prob)
fru_fpr, fru_tpr, fru_thresholds = roc_curve(y_test, fru_pred_prob)

# Compute the Area Under the ROC Curve (AUC) for each model
fcn_auc = roc_auc_score(y_test, fcn_pred_prob)
cnn_auc = roc_auc_score(y_test, cnn_pred_prob)
lstm_auc = roc_auc_score(y_test, lstm_pred_prob)
fru_auc = roc_auc_score(y_test, fru_pred_prob)

plt.figure(figsize=(20, 10), dpi=600)
plt.plot([0, 1], [0, 1], linestyle="--", lw=2,  label="Chance", alpha=0.8)
# Plot the ROC curve for each model
plt.plot(fcn_fpr, fcn_tpr, marker='.', label='FCN (auc = %0.3f)' % fcn_auc)
plt.plot(cnn_fpr, cnn_tpr, linestyle='-', label='CNN (auc = %0.3f)' % cnn_auc)
plt.plot(lstm_fpr, lstm_tpr, linestyle='-', label='LSTM (auc = %0.3f)' % lstm_auc)
plt.plot(fru_fpr, fru_tpr, linestyle='-', label='GRU (auc = %0.3f)' % fru_auc)

# plt.plot(fcn_fpr, fcn_tpr, label=f'FCN (AUC = {fcn_auc:.4f})')
# plt.plot(cnn_fpr, cnn_tpr, label=f'CNN (AUC = {cnn_auc:.4f})')
# plt.plot(lstm_fpr, lstm_tpr, label=f'LSTM (AUC = {lstm_auc:.4f})')
# plt.plot(fru_fpr, fru_tpr, label=f'GRU (AUC = {fru_auc:.4f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line representing random classifier
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend()
plt.legend(loc="lower right", fontsize=20, ncol=1)

plt.show()

X1=X.values

X1 = np.reshape(X1, (X1.shape[0], 1, X1.shape[1]))
# testx = np.reshape(testx, (testx.shape[0], 1, testx.shape[1]))

# X1 = np.reshape(X, (X.shape[0], 1, X.shape[1]))

# X1 = np.reshape(X, (X.shape[0], 1, X.shape[1]))
# X1 = np.reshape(X, (-1, 1, 1324))
# # # Convert output data to one-hot encoding
y = tf.keras.utils.to_categorical(y, 2)
# testy = tf.keras.utils.to_categorical(y_test, 2)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, confusion_matrix, matthews_corrcoef, roc_auc_score

# Assuming you have your data X and labels y
# X should have shape (num_samples, num_timesteps, num_features)
# y should have shape (num_samples,)

# Define the number of folds
num_folds = 5
num_timesteps = 1
# num_features = 153

# Initialize the lists to store the evaluation metrics
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
all_fpr = []
all_tpr = []
all_roc_auc = []

# Perform 5-fold cross-validation
kfold = KFold(n_splits=num_folds, shuffle=True)

for fold_index, (train_index, test_index) in enumerate(kfold.split(X1)):
    X_train, X_test = X1[train_index], X1[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Build the LSTM model
    lstm = Sequential()
    lstm.add(LSTM(units=128, input_shape=(num_timesteps, num_features)))
    lstm.add(Dropout(0.5))
    lstm.add(Dense(units=64, activation='relu'))
    lstm.add(Dropout(0.5))
    lstm.add(Dense(units=32, activation='relu'))
    lstm.add(Dropout(0.5))
    lstm.add(Dense(units=2, activation='softmax'))
    lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    lstm.fit(X_train, y_train, epochs=3, batch_size=16, verbose=0)

    # Evaluate the model on the test set
    y_pred = lstm.predict(X_test)
    y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    fpr, tpr, _ = roc_curve(y_test[:, 1], y_pred[:, 1])
    roc_auc = roc_auc_score(y_test[:, 1], y_pred[:, 1])

    # Append scores to lists
    accuracy_scores.append(accuracy)
    precision_scores.append(precision)
    recall_scores.append(recall)
    f1_scores.append(f1)
    all_fpr.append(fpr)
    all_tpr.append(tpr)
    all_roc_auc.append(roc_auc)

# Calculate the average scores across all folds
average_accuracy = np.mean(accuracy_scores)
average_precision = np.mean(precision_scores)
average_recall = np.mean(recall_scores)
average_f1 = np.mean(f1_scores)
average_roc_auc = np.mean(all_roc_auc)

# Calculate the average FPR and TPR across all folds for each threshold
average_fpr = np.mean(all_fpr, axis=0)
average_tpr = np.mean(all_tpr, axis=0)

# Compute FPR and TPR for each fold separately
fpr_per_fold = all_fpr
tpr_per_fold = all_tpr

# Compute average FPR and TPR per threshold across all folds
average_fpr_per_threshold = np.mean(fpr_per_fold, axis=0)
average_tpr_per_threshold = np.mean(tpr_per_fold, axis=0)

# Plot ROC curve
# plt.figure()
plt.figure(figsize=(20, 10), dpi=600)

plt.plot(average_fpr, average_tpr, label='LSTM Average ROC curve (AUC = {:.3f})'.format(average_roc_auc))
for fold in range(num_folds):
    plt.plot(fpr_per_fold[fold], tpr_per_fold[fold],linestyle='-', label='LSTM Fold {} ROC curve (AUC = {:.3f})'.format(fold+1, all_roc_auc[fold]))
plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right", fontsize=20, ncol=1)

# plt.legend()
plt.show()

print("Average Accuracy:", average_accuracy)
print("Average Precision:", average_precision)
print("Average Recall:", average_recall)
print("Average F1 Score:", average_f1)
print("Average ROC AUC:", average_roc_auc)

print('LSTM')
accuracy_scores

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, confusion_matrix, matthews_corrcoef, roc_auc_score

# Assuming you have your data X and labels y
# X should have shape (num_samples, num_timesteps, num_features)
# y should have shape (num_samples,)

# Define the number of folds
num_folds = 5
num_timesteps = 1
# num_features = 153

# Initialize the lists to store the evaluation metrics
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
all_fpr = []
all_tpr = []
all_roc_auc = []

# Perform 5-fold cross-validation
kfold = KFold(n_splits=num_folds, shuffle=True)

for fold_index, (train_index, test_index) in enumerate(kfold.split(X1)):
    X_train, X_test = X1[train_index], X1[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Build the GRU model
    gru = Sequential()
    gru.add(GRU(units=256, input_shape=(num_timesteps, num_features)))
    gru.add(Dropout(0.5))  # Add dropout layer for regularization
    gru.add(Dense(units=128, activation='relu'))  # Add additional dense layer
    gru.add(Dropout(0.5))  # Add dropout layer for regularization
    gru.add(Dense(units=2, activation='softmax'))
    gru.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    gru.fit(X_train, y_train, epochs=3, batch_size=16, verbose=0)

    # Evaluate the model on the test set
    y_pred = gru.predict(X_test)
    y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    fpr, tpr, _ = roc_curve(y_test[:, 1], y_pred[:, 1])
    roc_auc = roc_auc_score(y_test[:, 1], y_pred[:, 1])

    # Append scores to lists
    accuracy_scores.append(accuracy)
    precision_scores.append(precision)
    recall_scores.append(recall)
    f1_scores.append(f1)
    all_fpr.append(fpr)
    all_tpr.append(tpr)
    all_roc_auc.append(roc_auc)

# Calculate the average scores across all folds
average_accuracy = np.mean(accuracy_scores)
average_precision = np.mean(precision_scores)
average_recall = np.mean(recall_scores)
average_f1 = np.mean(f1_scores)
average_roc_auc = np.mean(all_roc_auc)

# Calculate the average FPR and TPR across all folds for each threshold
average_fpr = np.mean(all_fpr, axis=0)
average_tpr = np.mean(all_tpr, axis=0)

# Compute FPR and TPR for each fold separately
fpr_per_fold = all_fpr
tpr_per_fold = all_tpr

# Compute average FPR and TPR per threshold across all folds
average_fpr_per_threshold = np.mean(fpr_per_fold, axis=0)
average_tpr_per_threshold = np.mean(tpr_per_fold, axis=0)

# Plot ROC curve
# plt.figure()
plt.figure(figsize=(20, 10), dpi=600)

plt.plot(average_fpr, average_tpr, label='GRU Average ROC curve (AUC = {:.3f})'.format(average_roc_auc))
for fold in range(num_folds):
    plt.plot(fpr_per_fold[fold], tpr_per_fold[fold], linestyle='-', label='GRU Fold {} ROC curve (AUC = {:.3f})'.format(fold+1, all_roc_auc[fold]))
plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right", fontsize=20, ncol=1)

# plt.legend()
plt.show()

print("Average Accuracy:", average_accuracy)
print("Average Precision:", average_precision)
print("Average Recall:", average_recall)
print("Average F1 Score:", average_f1)
print("Average ROC AUC:", average_roc_auc)
accuracy_scores



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, roc_auc_score

# Assuming you have your data X and labels y
# X should have shape (num_samples, num_timesteps, num_features)
# y should have shape (num_samples,)

# Define the number of folds
num_folds = 5
num_timesteps = 1
num_features = 1324

# Initialize the lists to store the evaluation metrics
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
all_fpr = []
all_tpr = []
all_roc_auc = []

# Perform 5-fold cross-validation
kfold = KFold(n_splits=num_folds, shuffle=True)

for fold_index, (train_index, test_index) in enumerate(kfold.split(X1)):
    X_train, X_test = X1[train_index], X1[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Reshape the input data
    X_train = X_train.reshape(-1, num_features)
    X_test = X_test.reshape(-1, num_features)

    # Build the FCN model
    fcn = Sequential([
        Flatten(input_shape=(num_features,)),  # Flatten the input sequence
        Dense(64, activation='sigmoid'),  # First fully-connected layer with 64 units and sigmoid activation
        Dense(32, activation='sigmoid'),  # Second fully-connected layer with 32 units and sigmoid activation
        Dense(2, activation='softmax')  # Output layer with 2 units and softmax activation
    ])
    fcn.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    fcn.fit(X_train, y_train, epochs=3, batch_size=16, verbose=0)

    # Evaluate the model on the test set
    y_pred = fcn.predict(X_test)
    y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    fpr, tpr, _ = roc_curve(y_test[:, 1], y_pred[:, 1])
    roc_auc = roc_auc_score(y_test[:, 1], y_pred[:, 1])

    # Append scores to lists
    accuracy_scores.append(accuracy)
    precision_scores.append(precision)
    recall_scores.append(recall)
    f1_scores.append(f1)
    all_fpr.append(fpr)
    all_tpr.append(tpr)
    all_roc_auc.append(roc_auc)

# Calculate the average scores across all folds
average_accuracy = np.mean(accuracy_scores)
average_precision = np.mean(precision_scores)
average_recall = np.mean(recall_scores)
average_f1 = np.mean(f1_scores)
average_roc_auc = np.mean(all_roc_auc)

# Calculate the average FPR and TPR across all folds for each threshold
average_fpr = np.mean(all_fpr, axis=0)
average_tpr = np.mean(all_tpr, axis=0)

# Compute FPR and TPR for each fold separately
fpr_per_fold = all_fpr
tpr_per_fold = all_tpr

# Compute average FPR and TPR per threshold across all folds
average_fpr_per_threshold = np.mean(fpr_per_fold, axis=0)
average_tpr_per_threshold = np.mean(tpr_per_fold, axis=0)

# Plot ROC curve
plt.figure(figsize=(20, 10), dpi=600)

plt.plot(average_fpr, average_tpr, label='FCN Average ROC curve (AUC = {:.3f})'.format(average_roc_auc))
for fold in range(num_folds):
    plt.plot(fpr_per_fold[fold], tpr_per_fold[fold], linestyle='-', label='FCN Fold {} ROC curve (AUC = {:.3f})'.format(fold+1, all_roc_auc[fold]))
plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right", fontsize=20, ncol=1)

plt.show()

print("Average Accuracy:", average_accuracy)
print("Average Precision:", average_precision)
print("Average Recall:", average_recall)
print("Average F1 Score:", average_f1)
print("Average ROC AUC:", average_roc_auc)
accuracy_scores





import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import accuracy_score, roc_curve, confusion_matrix, matthews_corrcoef, roc_auc_score

# Assuming you have your data X and labels y
# X should have shape (num_samples, num_timesteps, num_features)
# y should have shape (num_samples,)

# Define the number of folds
num_folds = 5
num_timesteps = 1
# num_features = 153

# Initialize the lists to store the evaluation metrics
accuracy_scores = []
mcc_scores = []
sen_scores = []
spe_scores = []
all_fpr = []
all_tpr = []
all_roc_auc = []

# Perform 5-fold cross-validation
kfold = KFold(n_splits=num_folds, shuffle=True)

for fold_index, (train_index, test_index) in enumerate(kfold.split(X1)):
    X_train, X_test = X1[train_index], X1[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Build the LSTM model
    lstm = Sequential()
    lstm.add(LSTM(units=256, input_shape=(num_timesteps, num_features)))
    lstm.add(Dropout(0.5))  # Add dropout layer for regularization
    lstm.add(Dense(units=128, activation='relu'))  # Add additional dense layer
    lstm.add(Dropout(0.5))  # Add dropout layer for regularization
    lstm.add(Dense(units=2, activation='softmax'))
    lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    lstm.fit(X_train, y_train, epochs=3, batch_size=16, verbose=0)

    # Evaluate the model on the test set
    y_pred = lstm.predict(X_test)
    y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    fpr, tpr, _ = roc_curve(y_test[:, 1], y_pred[:, 1])
    roc_auc = roc_auc_score(y_test[:, 1], y_pred[:, 1])

    # Append scores to lists
    accuracy_scores.append(accuracy)
    mcc_scores.append(matthews_corrcoef(y_test[:, 1], y_pred[:, 1]))
    sen_scores.append(confusion_matrix(y_test[:, 1], y_pred[:, 1])[1, 1] / np.sum(y_test[:, 1]))
    spe_scores.append(confusion_matrix(y_test[:, 1], y_pred[:, 1])[0, 0] / np.sum(y_test[:, 0]))
    all_fpr.append(fpr)
    all_tpr.append(tpr)
    all_roc_auc.append(roc_auc)

# Calculate the average scores across all folds
average_accuracy = np.mean(accuracy_scores)
average_mcc = np.mean(mcc_scores)
average_sen = np.mean(sen_scores)
average_spe = np.mean(spe_scores)
average_roc_auc = np.mean(all_roc_auc)

# Calculate the average FPR and TPR across all folds for each threshold
average_fpr = np.mean(all_fpr, axis=0)
average_tpr = np.mean(all_tpr, axis=0)

# Compute FPR and TPR for each fold separately
fpr_per_fold = all_fpr
tpr_per_fold = all_tpr

# Compute average FPR and TPR per threshold across all folds
average_fpr_per_threshold = np.mean(fpr_per_fold, axis=0)
average_tpr_per_threshold = np.mean(tpr_per_fold, axis=0)

# Plot ROC curve
# plt.figure()
plt.figure(figsize=(20, 10), dpi=600)

plt.plot(average_fpr, average_tpr, label='Average ROC curve (AUC = {:.2f})'.format(average_roc_auc))
for fold in range(num_folds):
    plt.plot(fpr_per_fold[fold], tpr_per_fold[fold], label='Fold {} ROC curve (AUC = {:.2f})'.format(fold+1, all_roc_auc[fold]))
plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right", fontsize=20, ncol=1)

# plt.legend()
plt.show()

print("Average Accuracy:", average_accuracy)
print("Average MCC:", average_mcc)
print("Average SEN:", average_sen)
print("Average SPE:", average_spe)
print("Average ROC AUC:", average_roc_auc)
accuracy_scores

print("Average Accuracy:", average_accuracy)
print("Average MCC:", average_mcc)
print("Average SEN:", average_sen)
print("Average SPE:", average_spe)
print("Average ROC AUC:", average_roc_auc)
accuracy_scores

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, roc_auc_score

# Assuming you have your data X and labels y
# X should have shape (num_samples, num_timesteps, num_features)
# y should have shape (num_samples,)

# Define the number of folds
num_folds = 5
num_timesteps = 1
num_features = 1324

# Initialize the lists to store the evaluation metrics
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
all_fpr = []
all_tpr = []
all_roc_auc = []

# Perform 5-fold cross-validation
kfold = KFold(n_splits=num_folds, shuffle=True)

for fold_index, (train_index, test_index) in enumerate(kfold.split(X1)):
    X_train, X_test = X1[train_index], X1[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Reshape the input data
    X_train = np.reshape(X_train, (X_train.shape[0], num_features, num_timesteps))
    X_test = np.reshape(X_test, (X_test.shape[0], num_features, num_timesteps))

    # Build the CNN model
    modelcnn = Sequential()
    modelcnn.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(num_features, num_timesteps)))
    modelcnn.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
    modelcnn.add(Dropout(0.5))
    modelcnn.add(MaxPooling1D(pool_size=2))
    modelcnn.add(Flatten())
    modelcnn.add(Dense(100, activation='relu'))
    modelcnn.add(Dropout(0.5))
    modelcnn.add(Dense(50, activation='relu'))
    modelcnn.add(Dense(2, activation='softmax'))
    modelcnn.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    modelcnn.fit(X_train, y_train, epochs=3, batch_size=16, verbose=0)

    # Evaluate the model on the test set
    y_pred = modelcnn.predict(X_test)
    y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    # fpr, tpr, _ = roc_curve(y_test, y_pred)
    # roc_auc = roc_auc_score(y_test, y_pred)
    fpr, tpr, _ = roc_curve(y_test[:, 1], y_pred[:, 1])
    roc_auc = roc_auc_score(y_test[:, 1], y_pred[:, 1])

    # Append scores to lists
    accuracy_scores.append(accuracy)
    precision_scores.append(precision)
    recall_scores.append(recall)
    f1_scores.append(f1)
    all_fpr.append(fpr)
    all_tpr.append(tpr)
    all_roc_auc.append(roc_auc)

# Calculate the average scores across all folds
average_accuracy = np.mean(accuracy_scores)
average_precision = np.mean(precision_scores)
average_recall = np.mean(recall_scores)
average_f1 = np.mean(f1_scores)
average_roc_auc = np.mean(all_roc_auc)

# Calculate the average FPR and TPR across all folds for each threshold
average_fpr = np.mean(all_fpr, axis=0)
average_tpr = np.mean(all_tpr, axis=0)

# Compute FPR and TPR for each fold separately
fpr_per_fold = all_fpr
tpr_per_fold = all_tpr

# Compute average FPR and TPR per threshold across all folds
average_fpr_per_threshold = np.mean(fpr_per_fold, axis=0)
average_tpr_per_threshold = np.mean(tpr_per_fold, axis=0)

# Plot ROC curve
plt.figure(figsize=(20, 10), dpi=600)

plt.plot(average_fpr, average_tpr, label='CNN Average ROC curve (AUC = {:.3f})'.format(average_roc_auc))
for fold in range(num_folds):
    plt.plot(fpr_per_fold[fold], tpr_per_fold[fold], linestyle='-', label='CNN Fold {} ROC curve (AUC = {:.3f})'.format(fold+1, all_roc_auc[fold]))
plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right", fontsize=20, ncol=1)

plt.show()

print("Average Accuracy:", average_accuracy)
print("Average Precision:", average_precision)
print("Average Recall:", average_recall)
print("Average F1 Score:", average_f1)
print("Average ROC AUC:", average_roc_auc)

accuracy_scores

LSTM
[0.8415605095541401,
 0.8455414012738853,
 0.8479299363057324,
 0.8670382165605095,
 0.8511146496815286]
 Gru
 [0.875,
 0.8383757961783439,
 0.8375796178343949,
 0.856687898089172,
 0.8646496815286624]
 FCN
 [0.8375796178343949,
 0.856687898089172,
 0.8168789808917197,
 0.8288216560509554,
 0.8176751592356688]

import numpy as np
#lst_accu_stratifiedlgbm5.append(np.mean(lst_accu_stratifiedlgbm5))
st10 = {'Accuracy':[0.8375796178343949,
 0.856687898089172,
 0.8168789808917197,
 0.8288216560509554,
 0.8176751592356688],
        'folds': [1,2,3,4,5],
      'algo': 'stack'}
st10=pd.DataFrame(st10)

rf10 = {'Accuracy':[0.875,
 0.8383757961783439,
 0.8375796178343949,
 0.856687898089172,
 0.8646496815286624],
        'folds': [1,2,3,4,5],
      'algo': 'rf'}
rf10=pd.DataFrame(rf10)


lgbm10 = {'Accuracy':[0.8415605095541401,
 0.8455414012738853,
 0.8479299363057324,
 0.8670382165605095,
 0.8511146496815286],
        'folds': [1,2,3,4,5],
      'algo': 'lgbm'}
lgbm10=pd.DataFrame(lgbm10)


ada10 = {'Accuracy':[0.8343949044585988,
 0.8431528662420382,
 0.822452229299363,
 0.8288216560509554,
 0.8415605095541401],
        'folds': [1,2,3,4,5],
      'algo': 'ridge'}
ada10=pd.DataFrame(ada10)


v10 = pd.concat([rf10,ada10,lgbm10,st10], axis=0)

from matplotlib import pyplot
import seaborn
#import mylib
a4_dims = (10, 6)
fig, ax = pyplot.subplots(figsize=a4_dims,dpi=600)
seaborn.violinplot(ax=ax, y=v10["Accuracy"], x=v10["folds"])





from keras.layers import LSTM, Dense, Dropout
num_timesteps,num_features=1,1324
lstm = Sequential()
lstm.add(LSTM(units=128, input_shape=(num_timesteps, num_features)))
lstm.add(Dropout(0.5))  # Add dropout layer for regularization
lstm.add(Dense(units=64, activation='relu'))  # Add additional dense layer
lstm.add(Dropout(0.5))  # Add dropout layer for regularization
lstm.add(Dense(units=32, activation='relu'))  # Add additional dense layer
lstm.add(Dropout(0.5))  # Add dropout layer for regularization
lstm.add(Dense(units=2, activation='softmax'))
lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# import numpy as np
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Conv1D, LSTM, Dropout, Dense
# from tensorflow.keras.layers import Reshape

# model = Sequential()
# model.add(Conv1D(filters=64, kernel_size=3, activation='relu', padding='valid', input_shape=(1324, 1)))
# model.add(Reshape((model.output_shape[1], model.output_shape[2] * model.output_shape[2])))
# model.add(LSTM(32, return_sequences=True))
# model.add(Dropout(0.5))
# model.add(Dense(2, activation='softmax'))
# model.summary()

trainx1 = np.reshape(trainx, (trainx1.shape[0], trainx1.shape[2], trainx1.shape[1]))
testx1 = np.reshape(test1x, (testx1.shape[0], testx1.shape[2], testx1.shape[1]))

trainx1.shape

trainx1 = trainx.reshape(-1, 1324, 1)
testx1 = testx.reshape(-1, 1324, 1)

trainx=X_train.values
testx=X_test.values

# trainx = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
# testx = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# model.fit(X_train,y_train)
lstm.fit(trainx1, y_train, validation_data=(testx1,y_test), epochs=5, verbose=1)



